/*
-- Query: select * from company_association
LIMIT 0, 1000

-- Date: 2020-04-22 11:14
*/
INSERT INTO `company_association` (`A_User_id`,`C_Tag_ID`,`role`,`no_of_years`,`is_current`) VALUES (1111502,2,'Engineer',2,1);
INSERT INTO `company_association` (`A_User_id`,`C_Tag_ID`,`role`,`no_of_years`,`is_current`) VALUES (1111503,2,'Analyst',3,1);
INSERT INTO `company_association` (`A_User_id`,`C_Tag_ID`,`role`,`no_of_years`,`is_current`) VALUES (1111504,4,'Vice president',8,1);
INSERT INTO `company_association` (`A_User_id`,`C_Tag_ID`,`role`,`no_of_years`,`is_current`) VALUES (1111505,5,'Developer',2,1);
INSERT INTO `company_association` (`A_User_id`,`C_Tag_ID`,`role`,`no_of_years`,`is_current`) VALUES (1111506,6,'Architect',3,1);
INSERT INTO `company_association` (`A_User_id`,`C_Tag_ID`,`role`,`no_of_years`,`is_current`) VALUES (1111507,7,'Vice President',8,1);
INSERT INTO `company_association` (`A_User_id`,`C_Tag_ID`,`role`,`no_of_years`,`is_current`) VALUES (1111508,8,'Sr Engineer',4,1);
INSERT INTO `company_association` (`A_User_id`,`C_Tag_ID`,`role`,`no_of_years`,`is_current`) VALUES (1111509,8,'Engineer',2,1);
INSERT INTO `company_association` (`A_User_id`,`C_Tag_ID`,`role`,`no_of_years`,`is_current`) VALUES (1111510,8,'Analyst',2,1);
INSERT INTO `company_association` (`A_User_id`,`C_Tag_ID`,`role`,`no_of_years`,`is_current`) VALUES (1111511,8,'Vice president',8,1);
INSERT INTO `company_association` (`A_User_id`,`C_Tag_ID`,`role`,`no_of_years`,`is_current`) VALUES (1111512,8,'Developer',3,1);
INSERT INTO `company_association` (`A_User_id`,`C_Tag_ID`,`role`,`no_of_years`,`is_current`) VALUES (1111513,13,'Architect',8,0);
INSERT INTO `company_association` (`A_User_id`,`C_Tag_ID`,`role`,`no_of_years`,`is_current`) VALUES (1111514,14,'Vice President',2,0);
INSERT INTO `company_association` (`A_User_id`,`C_Tag_ID`,`role`,`no_of_years`,`is_current`) VALUES (1111515,15,'Sr Engineer',3,0);
INSERT INTO `company_association` (`A_User_id`,`C_Tag_ID`,`role`,`no_of_years`,`is_current`) VALUES (1111601,16,'Engineer',8,0);
INSERT INTO `company_association` (`A_User_id`,`C_Tag_ID`,`role`,`no_of_years`,`is_current`) VALUES (1111602,17,'Analyst',4,1);
INSERT INTO `company_association` (`A_User_id`,`C_Tag_ID`,`role`,`no_of_years`,`is_current`) VALUES (1111603,18,'Vice president',2,1);
INSERT INTO `company_association` (`A_User_id`,`C_Tag_ID`,`role`,`no_of_years`,`is_current`) VALUES (1111604,19,'Engineer',2,1);
INSERT INTO `company_association` (`A_User_id`,`C_Tag_ID`,`role`,`no_of_years`,`is_current`) VALUES (1111605,19,'Analyst',2,1);
INSERT INTO `company_association` (`A_User_id`,`C_Tag_ID`,`role`,`no_of_years`,`is_current`) VALUES (1111606,19,'Vice president',3,1);
INSERT INTO `company_association` (`A_User_id`,`C_Tag_ID`,`role`,`no_of_years`,`is_current`) VALUES (1111607,22,'Developer',8,1);
INSERT INTO `company_association` (`A_User_id`,`C_Tag_ID`,`role`,`no_of_years`,`is_current`) VALUES (1111608,23,'Architect',2,1);
INSERT INTO `company_association` (`A_User_id`,`C_Tag_ID`,`role`,`no_of_years`,`is_current`) VALUES (1111609,24,'Vice President',3,1);
INSERT INTO `company_association` (`A_User_id`,`C_Tag_ID`,`role`,`no_of_years`,`is_current`) VALUES (1111610,25,'Sr Engineer',8,1);
INSERT INTO `company_association` (`A_User_id`,`C_Tag_ID`,`role`,`no_of_years`,`is_current`) VALUES (1111611,25,'Engineer',4,1);
INSERT INTO `company_association` (`A_User_id`,`C_Tag_ID`,`role`,`no_of_years`,`is_current`) VALUES (1111612,25,'Analyst',2,1);
INSERT INTO `company_association` (`A_User_id`,`C_Tag_ID`,`role`,`no_of_years`,`is_current`) VALUES (1111613,28,'Vice president',2,0);
INSERT INTO `company_association` (`A_User_id`,`C_Tag_ID`,`role`,`no_of_years`,`is_current`) VALUES (1111614,2,'Developer',2,0);
INSERT INTO `company_association` (`A_User_id`,`C_Tag_ID`,`role`,`no_of_years`,`is_current`) VALUES (1111615,2,'Architect',3,0);
INSERT INTO `company_association` (`A_User_id`,`C_Tag_ID`,`role`,`no_of_years`,`is_current`) VALUES (1111701,2,'Vice President',8,0);
INSERT INTO `company_association` (`A_User_id`,`C_Tag_ID`,`role`,`no_of_years`,`is_current`) VALUES (1111702,2,'Sr Engineer',2,1);
INSERT INTO `company_association` (`A_User_id`,`C_Tag_ID`,`role`,`no_of_years`,`is_current`) VALUES (1111703,6,'Engineer',3,1);
INSERT INTO `company_association` (`A_User_id`,`C_Tag_ID`,`role`,`no_of_years`,`is_current`) VALUES (1111704,6,'Analyst',8,1);
INSERT INTO `company_association` (`A_User_id`,`C_Tag_ID`,`role`,`no_of_years`,`is_current`) VALUES (1111705,6,'Vice president',4,1);
INSERT INTO `company_association` (`A_User_id`,`C_Tag_ID`,`role`,`no_of_years`,`is_current`) VALUES (1111706,6,'Engineer',2,1);
INSERT INTO `company_association` (`A_User_id`,`C_Tag_ID`,`role`,`no_of_years`,`is_current`) VALUES (1111707,6,'Analyst',2,1);
INSERT INTO `company_association` (`A_User_id`,`C_Tag_ID`,`role`,`no_of_years`,`is_current`) VALUES (1111708,6,'Vice president',2,1);
INSERT INTO `company_association` (`A_User_id`,`C_Tag_ID`,`role`,`no_of_years`,`is_current`) VALUES (1111709,6,'Developer',3,1);
INSERT INTO `company_association` (`A_User_id`,`C_Tag_ID`,`role`,`no_of_years`,`is_current`) VALUES (1111710,13,'Architect',8,1);
INSERT INTO `company_association` (`A_User_id`,`C_Tag_ID`,`role`,`no_of_years`,`is_current`) VALUES (1111711,14,'Vice President',2,1);
INSERT INTO `company_association` (`A_User_id`,`C_Tag_ID`,`role`,`no_of_years`,`is_current`) VALUES (1111712,15,'Sr Engineer',3,1);
INSERT INTO `company_association` (`A_User_id`,`C_Tag_ID`,`role`,`no_of_years`,`is_current`) VALUES (1111713,16,'Engineer',8,0);
INSERT INTO `company_association` (`A_User_id`,`C_Tag_ID`,`role`,`no_of_years`,`is_current`) VALUES (1111714,17,'Analyst',4,0);
INSERT INTO `company_association` (`A_User_id`,`C_Tag_ID`,`role`,`no_of_years`,`is_current`) VALUES (1111715,18,'Vice president',2,0);
INSERT INTO `company_association` (`A_User_id`,`C_Tag_ID`,`role`,`no_of_years`,`is_current`) VALUES (1111801,19,'Developer',2,0);
INSERT INTO `company_association` (`A_User_id`,`C_Tag_ID`,`role`,`no_of_years`,`is_current`) VALUES (1111802,20,'Architect',2,1);
INSERT INTO `company_association` (`A_User_id`,`C_Tag_ID`,`role`,`no_of_years`,`is_current`) VALUES (1111803,21,'Vice President',3,1);
INSERT INTO `company_association` (`A_User_id`,`C_Tag_ID`,`role`,`no_of_years`,`is_current`) VALUES (1111804,22,'Sr Engineer',8,1);
INSERT INTO `company_association` (`A_User_id`,`C_Tag_ID`,`role`,`no_of_years`,`is_current`) VALUES (1111805,23,'Engineer',2,1);
INSERT INTO `company_association` (`A_User_id`,`C_Tag_ID`,`role`,`no_of_years`,`is_current`) VALUES (1111806,24,'Analyst',3,1);
INSERT INTO `company_association` (`A_User_id`,`C_Tag_ID`,`role`,`no_of_years`,`is_current`) VALUES (1111807,25,'Vice president',8,1);
INSERT INTO `company_association` (`A_User_id`,`C_Tag_ID`,`role`,`no_of_years`,`is_current`) VALUES (1111808,26,'Engineer',4,1);
INSERT INTO `company_association` (`A_User_id`,`C_Tag_ID`,`role`,`no_of_years`,`is_current`) VALUES (1111809,27,'Analyst',2,1);
INSERT INTO `company_association` (`A_User_id`,`C_Tag_ID`,`role`,`no_of_years`,`is_current`) VALUES (1111810,27,'Vice president',2,1);
INSERT INTO `company_association` (`A_User_id`,`C_Tag_ID`,`role`,`no_of_years`,`is_current`) VALUES (1111811,2,'Developer',2,1);
INSERT INTO `company_association` (`A_User_id`,`C_Tag_ID`,`role`,`no_of_years`,`is_current`) VALUES (1111812,3,'Architect',3,1);
INSERT INTO `company_association` (`A_User_id`,`C_Tag_ID`,`role`,`no_of_years`,`is_current`) VALUES (1111813,4,'Vice President',8,0);
INSERT INTO `company_association` (`A_User_id`,`C_Tag_ID`,`role`,`no_of_years`,`is_current`) VALUES (1111814,5,'Sr Engineer',2,0);
INSERT INTO `company_association` (`A_User_id`,`C_Tag_ID`,`role`,`no_of_years`,`is_current`) VALUES (1111815,6,'Engineer',3,0);
INSERT INTO `company_association` (`A_User_id`,`C_Tag_ID`,`role`,`no_of_years`,`is_current`) VALUES (1111901,7,'Analyst',8,0);
INSERT INTO `company_association` (`A_User_id`,`C_Tag_ID`,`role`,`no_of_years`,`is_current`) VALUES (1111902,8,'Vice president',4,1);
INSERT INTO `company_association` (`A_User_id`,`C_Tag_ID`,`role`,`no_of_years`,`is_current`) VALUES (1111903,9,'Developer',2,1);
INSERT INTO `company_association` (`A_User_id`,`C_Tag_ID`,`role`,`no_of_years`,`is_current`) VALUES (1111904,10,'Architect',2,1);
INSERT INTO `company_association` (`A_User_id`,`C_Tag_ID`,`role`,`no_of_years`,`is_current`) VALUES (1111905,11,'Vice President',2,1);
INSERT INTO `company_association` (`A_User_id`,`C_Tag_ID`,`role`,`no_of_years`,`is_current`) VALUES (1111906,12,'Sr Engineer',3,1);
INSERT INTO `company_association` (`A_User_id`,`C_Tag_ID`,`role`,`no_of_years`,`is_current`) VALUES (1111907,13,'Engineer',8,1);
INSERT INTO `company_association` (`A_User_id`,`C_Tag_ID`,`role`,`no_of_years`,`is_current`) VALUES (1111908,14,'Analyst',2,1);
INSERT INTO `company_association` (`A_User_id`,`C_Tag_ID`,`role`,`no_of_years`,`is_current`) VALUES (1111909,15,'Vice president',3,1);
INSERT INTO `company_association` (`A_User_id`,`C_Tag_ID`,`role`,`no_of_years`,`is_current`) VALUES (1111910,16,'Engineer',8,1);
INSERT INTO `company_association` (`A_User_id`,`C_Tag_ID`,`role`,`no_of_years`,`is_current`) VALUES (1111911,17,'Analyst',4,1);
INSERT INTO `company_association` (`A_User_id`,`C_Tag_ID`,`role`,`no_of_years`,`is_current`) VALUES (1111912,18,'Vice president',2,1);
INSERT INTO `company_association` (`A_User_id`,`C_Tag_ID`,`role`,`no_of_years`,`is_current`) VALUES (1111913,19,'Developer',2,0);
INSERT INTO `company_association` (`A_User_id`,`C_Tag_ID`,`role`,`no_of_years`,`is_current`) VALUES (1111914,20,'Architect',2,0);
INSERT INTO `company_association` (`A_User_id`,`C_Tag_ID`,`role`,`no_of_years`,`is_current`) VALUES (1111915,21,'Vice President',3,0);
INSERT INTO `company_association` (`A_User_id`,`C_Tag_ID`,`role`,`no_of_years`,`is_current`) VALUES (1112001,22,'Sr Engineer',8,0);
INSERT INTO `company_association` (`A_User_id`,`C_Tag_ID`,`role`,`no_of_years`,`is_current`) VALUES (1112002,23,'Engineer',2,1);
INSERT INTO `company_association` (`A_User_id`,`C_Tag_ID`,`role`,`no_of_years`,`is_current`) VALUES (1112003,24,'Analyst',3,1);
INSERT INTO `company_association` (`A_User_id`,`C_Tag_ID`,`role`,`no_of_years`,`is_current`) VALUES (1112004,25,'Vice president',8,1);
INSERT INTO `company_association` (`A_User_id`,`C_Tag_ID`,`role`,`no_of_years`,`is_current`) VALUES (1112005,26,'Developer',4,1);
INSERT INTO `company_association` (`A_User_id`,`C_Tag_ID`,`role`,`no_of_years`,`is_current`) VALUES (1112006,27,'Architect',2,1);
INSERT INTO `company_association` (`A_User_id`,`C_Tag_ID`,`role`,`no_of_years`,`is_current`) VALUES (1112007,28,'Vice President',2,1);
INSERT INTO `company_association` (`A_User_id`,`C_Tag_ID`,`role`,`no_of_years`,`is_current`) VALUES (1112008,2,'Sr Engineer',2,1);
INSERT INTO `company_association` (`A_User_id`,`C_Tag_ID`,`role`,`no_of_years`,`is_current`) VALUES (1112009,3,'Engineer',3,1);
INSERT INTO `company_association` (`A_User_id`,`C_Tag_ID`,`role`,`no_of_years`,`is_current`) VALUES (1112010,3,'Analyst',8,1);
INSERT INTO `company_association` (`A_User_id`,`C_Tag_ID`,`role`,`no_of_years`,`is_current`) VALUES (1112011,3,'Vice president',2,1);
INSERT INTO `company_association` (`A_User_id`,`C_Tag_ID`,`role`,`no_of_years`,`is_current`) VALUES (1112012,6,'Engineer',3,1);
INSERT INTO `company_association` (`A_User_id`,`C_Tag_ID`,`role`,`no_of_years`,`is_current`) VALUES (1112013,7,'Analyst',8,0);
INSERT INTO `company_association` (`A_User_id`,`C_Tag_ID`,`role`,`no_of_years`,`is_current`) VALUES (1112014,7,'Vice president',4,0);
INSERT INTO `company_association` (`A_User_id`,`C_Tag_ID`,`role`,`no_of_years`,`is_current`) VALUES (1112015,7,'Developer',2,0);
INSERT INTO `company_association` (`A_User_id`,`C_Tag_ID`,`role`,`no_of_years`,`is_current`) VALUES (1111315,10,'Architect',2,0);
